#!/bin/sh

ip=/usr/bin/ip

fw_init() {
    echo "===>>> Initializing sshguard blackhole blocking"
}

fw_block() {
    echo "===>>> Blocking $1/$3 (blackhole)"
    $ip route add blackhole $1/$3
}

fw_release() {
    echo "===>>> Releasing $1/$3 (blackhole)"
    $ip route del blackhole $1/$3
}

fw_flush() {
    echo "===>>> Flushing blocked addresses (blackhole)"
    $ip route flush type blackhole
}

fw_fin() {
    echo "===>>> Finished sshguard blackhole blocking"
}

die() {
    echo "$(basename "$0"): $2" >&2
    exit "$1"
}

fw_init || die 69 "Could not initialize firewall"

cleanup() {
    trap "" EXIT
    if [ "YES" = "$flushonexit" ]; then
        fw_flush
    fi
    fw_fin
    exit
}

trap cleanup EXIT INT TERM

while read -r cmd address addrtype cidr; do
    case $cmd in
        block)
            fw_block "$address" "$addrtype" "$cidr";;
        release)
            fw_release "$address" "$addrtype" "$cidr";;
        flush)
            fw_flush;;
        flushonexit)
            flushonexit=YES;;
        *)
            die 65 "Invalid command";;
    esac
done
