#!/usr/bin/env bash
# Copyright 2011, Nico R. Wohlgemuth <nico@lifeisabug.com>

# For FreeBSD route(8)
# Run me from /etc/rc.local

if [[ $UID -ne 0 ]]; then
   echo "This script requires to be run as root!"
   exit 1
fi

IPFILE="/etc/nullrouteips"

if [[ ! -f "$IPFILE" ]]; then
   echo "$0: $IPFILE is missing, exiting."
   exit 2
fi

declare -a nullroutes=( $(cat $IPFILE) )

echo "$0: Loading nullroute(s)..."

for ip in ${nullroutes[@]}
do
   route add -host $ip 127.0.0.1 -blackhole
done

echo "$0: ${#nullroutes[@]} nullroute(s) loaded."
