#!/usr/bin/env bash
# Copyright 2011, Nico R. Wohlgemuth <nico@lifeisabug.com>

# For FreeBSD route(8)

if [[ $UID -ne 0 ]]; then
   echo "This script requires to be run as root!"
   exit 1
fi

if [[ $# -ne 1 ]]; then
   echo "Usage: $0 <IP-Address>"
   exit 2
fi

IP="$1"
IPFILE="/etc/nullrouteips"

if [[ "$IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
   route add -host $IP 127.0.0.1 -blackhole
   echo $IP >> $IPFILE
   echo "$IP has been nullrouted (blackholed) and inserted into $IPFILE."
else
   echo "$IP is not a valid IP!"
   exit 3
fi
